name: create-relese-note

on:
  push:
    branches:
      - production

concurrency:
  group: ${{ github.workflow }}

jobs:
  create-release-note:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set Release Tag
        env:
          TZ: "Asia/Tokyo"
        run: |
          tag=$(date '+%Y%m%d-%H%M%S')
          echo "RELEASE_TAG=${tag}" >> $GITHUB_ENV
      - name: Create Release Note
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { RELEASE_TAG } = process.env;
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: RELEASE_TAG,
              target_commitish: 'production',
              generate_release_notes: true,
            });
